export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const BASKET_REQUEST = "BASKET_REQUEST";
export const CATALOG_REQUEST = "CATALOG_REQUEST";
export const SIGH_IN_ERROR = "SIGH_IN_ERROR";
export const SIGH_IN_SUCCESSFULLY = "SIGH_IN_SUCCESSFULLY";
export const BASKET_LOAD_SUCCESSFULLY = "BASKET_LOAD_SUCCESSFULLY";
export const CATALOG_FILTER_ITEM_LOAD_SUCCESSFULLY =
  "CATALOG_FILTER_ITEM_LOAD_SUCCESSFULLY";
