export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const BASKET_REQUEST = "BASKET_REQUEST";
export const BASKET_LOAD_SUCCESSFULLY = "BASKET_LOAD_SUCCESSFULLY";
